version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
      - image: trufflesuite/ganache-cli:v6.8.1-beta.0
        command: ganache-cli -e 10000000000 -a 100 -k istanbul
    working_directory: ~/repo
    steps:
      - checkout
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git submodule sync
      - run: git submodule update --init --recursive

      - run: npm i
      
      - run: npm run lintNoFix
      - run: npm run test

      # save checkout & build
      - persist_to_workspace:
          root: '..'
          paths:
            - repo
            - .ssh

  publish:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
                - artifacts
            tags:
              only: /^v.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
